sudo: required
dist: trusty
cache:
  directories:
    - node_modules
    - ~/.selenium-assistant
language: node_js
node_js:
  - "stable"

addons:
  apt_packages:
    - pandoc
    - texlive-full
    - inkscape

before_install:
  - rvm install ruby-2.3.3
  - rvm --default use 2.3.3
  - gem install bundler
  - rvm . do bundle install

install:
  - npm install firebase-tools -g
  - npm install

script:
  - ./utils/build-book.sh
  - if [[ "$TRAVIS_BRANCH" = "master" && "$TRAVIS_OS_NAME" = "linux" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then firebase deploy travis encrypt "1/LtCMwFT5ffFvm1dD4e2Jr9IUJEzX9vvtVb-6MCWV-Rw" --add deploy.token  --project donboulton-210120 --non-interactive; fi