source: ./build
destination: ./build/_site/
layouts_dir: ./jekyll/_layouts/
includes_dir: ./jekyll/_includes/
url: https://donaldboulton.github.io/web-push-book/

exclude:
  - _content/chapter-01/00-info.md
  - _content/epub-metadata.yaml
firebase: 
  - serviceAccount: "firebase-adminsdk-w6981@donboulton-210120.iam.gserviceaccount.com"
  - apiKey: "AIzaSyDE2FsxAT0d3nROmfIZKcWoAuJNyzcmOZA"
  - publicFacingName: "project-642731329222"
  - name: "project-642731329222"
  - secret: "HhbGUueQ7G6lU0VPiwi2Uw6ovK0YOYaY7wUI9WuR"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "book-page"

collections:
  content:
    output: true
    permalink: /:path/
