source: ./build
destination: ./build/_site/
layouts_dir: ./jekyll/_layouts/
includes_dir: ./jekyll/_includes/
url: https://donaldboulton.github.io/web-push-book/

exclude:
  - _content/chapter-01/00-info.md
  - _content/epub-metadata.yaml

defaults:
  -
    scope:
      path: ""
    values:
      layout: "book-page"

collections:
  content:
    output: true
    permalink: /:path/
